"""BibTeX export helpers."""

from __future__ import annotations

import logging
import re
from datetime import datetime
from pathlib import Path

from hypo_research.core.models import PaperResult

logger = logging.getLogger(__name__)


def generate_bibtex(
    papers: list[PaperResult],
    output_path: Path,
    query: str | None = None,
) -> Path:
    """Generate a BibTeX file from paper results."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    used_keys: dict[str, int] = {}
    entries: list[str] = []
    for paper in papers:
        entry = _paper_to_bibtex_entry(paper, used_keys)
        if entry:
            entries.append(entry)

    header = [
        f"% Generated by Hypo-Research on {datetime.now().isoformat()}",
        f"% Query: {query or 'unknown'}",
        f"% Papers: {len(entries)}",
        "",
    ]
    output_path.write_text(
        "\n".join(header + entries) + ("\n" if entries else ""),
        encoding="utf-8",
    )
    return output_path


def paper_to_bibtex_entry(paper: PaperResult) -> str:
    """Convert a single PaperResult to a BibTeX entry string."""
    return _paper_to_bibtex_entry(paper, {})


def _paper_to_bibtex_entry(
    paper: PaperResult,
    used_keys: dict[str, int],
) -> str:
    if not paper.title or not paper.authors:
        logger.warning("Skipping BibTeX entry due to missing title/authors: %s", paper)
        return ""

    entry_type = _entry_type(paper)
    citation_key = _unique_key(_citation_key(paper), used_keys)

    fields: list[tuple[str, str]] = [
        ("title", _escape_bibtex(paper.title)),
        ("author", _format_authors(paper.authors)),
    ]
    if paper.year is not None:
        fields.append(("year", str(paper.year)))

    if paper.venue:
        fields.append((_venue_field_name(entry_type), _escape_bibtex(paper.venue)))

    if paper.doi:
        normalized_doi = paper.doi.lower().removeprefix("https://doi.org/")
        fields.append(("doi", normalized_doi))
        fields.append(("url", f"https://doi.org/{normalized_doi}"))
    elif paper.url:
        fields.append(("url", _escape_bibtex(paper.url)))

    if paper.abstract:
        fields.append(("abstract", _escape_bibtex(paper.abstract)))

    if paper.arxiv_id:
        fields.append(("eprint", paper.arxiv_id))
        fields.append(("archiveprefix", "arXiv"))
        primary_class = _arxiv_primary_class(paper)
        if primary_class:
            fields.append(("primaryclass", primary_class))

    lines = [f"@{entry_type}{{{citation_key},"]
    for field_name, value in fields:
        lines.append(f"  {field_name:<13} = {{{value}}},")
    lines.append("}")
    return "\n".join(lines)


def _entry_type(paper: PaperResult) -> str:
    venue = (paper.venue or "").lower()
    if paper.arxiv_id and not paper.venue:
        return "misc"
    if any(term in venue for term in ("conference", "symposium", "workshop")):
        return "inproceedings"
    if any(term in venue for term in ("journal", "transactions", "letters")):
        return "article"
    return "article"


def _venue_field_name(entry_type: str) -> str:
    if entry_type == "inproceedings":
        return "booktitle"
    if entry_type == "misc":
        return "howpublished"
    return "journal"


def _citation_key(paper: PaperResult) -> str:
    last_name = _author_last_name(paper.authors[0]) or "unknown"
    year = str(paper.year or "nodate")
    first_word = _first_title_word(paper.title)
    return f"{last_name}{year}{first_word}"


def _unique_key(base_key: str, used_keys: dict[str, int]) -> str:
    count = used_keys.get(base_key, 0)
    used_keys[base_key] = count + 1
    if count == 0:
        return base_key
    suffix = chr(ord("a") + count - 1)
    return f"{base_key}{suffix}"


def _format_authors(authors: list[str]) -> str:
    return " and ".join(_format_single_author(author) for author in authors)


def _format_single_author(author: str) -> str:
    parts = [part for part in author.split() if part]
    if len(parts) <= 1:
        return _escape_bibtex(author)
    last = _escape_bibtex(parts[-1])
    first = _escape_bibtex(" ".join(parts[:-1]))
    return f"{last}, {first}"


def _author_last_name(author: str) -> str:
    parts = [part for part in re.findall(r"[A-Za-z0-9]+", author.lower()) if part]
    if not parts:
        return "unknown"
    return parts[-1]


def _first_title_word(title: str) -> str:
    words = re.findall(r"[A-Za-z0-9]+", title.lower())
    return words[0] if words else "paper"


def _escape_bibtex(value: str) -> str:
    escaped = value.replace("\\", "\\\\")
    escaped = escaped.replace("&", "\\&")
    escaped = escaped.replace("_", "\\_")
    escaped = escaped.replace("%", "\\%")
    escaped = escaped.replace("#", "\\#")
    return escaped


def _arxiv_primary_class(paper: PaperResult) -> str | None:
    raw_primary_category = (paper.raw_response or {}).get("arxiv_primary_category")
    if isinstance(raw_primary_category, dict):
        term = raw_primary_category.get("term")
        if term:
            return str(term)
    if paper.venue and "." in paper.venue:
        return paper.venue
    return None
